theme = "onedark"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding", "version-control"]

[editor.soft-wrap]
enable = true
max-wrap = 25
